CART_HOST: cart.backend-{{ env }}.joindevops.fun
USER_HOST: user.backend-{{ env }}.joindevops.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.joindevops.fun
RABBITMQ_USER: roboshop
RABBITMQ_PASSWORD: roboshop123